version: '3.8'
services:
    cont-build:
        build: build-app
        volumes:
            - "mytarget:/work/boxfuse-sample-java-war-hello/target"

    myapp:
        image: tomcat:8.5-alpine
        volumes:
            - "mytarget:/usr/local/tomcat/webapps"
        ports:
            - "8080:8080"
        depends_on:
            - cont-build
volumes:
    mytarget:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './target'
